### ISSUE TITLE
Preview should go away if I'm not active

### ISSUE THREAD

**Issue by joeyguerra** [joeyguerra/devchitchat#24]
Given that I type something in the text box
When I delete it
And I am not currently "active" on the chat
Then the Message Preview goes away

**Comment by kijanawoodard** [comment]
Ha. I noticed that and didn't file an issue!

You're just as picky as we are!!!

-----Original Message-----

**Comment by ijoey** [comment]
:) It just now bothered me as I was reading the DDD group summary discussion and going off on a messaging tangent. Don't ask me why though.

On another note, I really like working on this project because it's giving me a chance to freakin' use GitHub. But now I want an issue "voting" feature so I know what item should be worked on next.
